.circleci/config.yml
Enable deployments to preprod and prod
=> ESWE-811 Backend

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/hmppscandidatematchingapi/integration/health/HealthCheckIntTest.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/hmppscandidatematchingapi/integration/health/InfoIntTest.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsjobsboardapi/config/CapturedSpringConfigValues.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsjobsboardapi/telemetry/TelemetryService.kt
Refactored some names to meet the coding standards:
- Renamed object mapper constant
- Renamed telemetry event creation function
=> ESWE-831 Renaming to code standards

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/health/HealthCheckIntTest.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/health/InfoIntTest.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/health/VersionOutputter.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/unit/messaging/OutboundEventsPublisherTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/unit/messaging/OutboundEventsServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/unit/repositories/RepositoriesTests.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/unit/service/JobsBoardProfileServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/unit/service/TelemetryServiceTest.kt
The purpose of this request is:
- Disable empty tests
- Comment some tests to avoid Gradle assemble errors that are happening on the Docker image. They will be restored when we have a clear testing strategy.
=> ESWE-831 Fix dev environment errors

helm_deploy/values-dev.yaml
Adds the missing Oauth endpoint for Dev
=> [ESWE-831] Add missing Oauth Dev endpoint

src/main/resources/application-dev.yml
This PR fixes the SSL mode for the dev environment.
=> [ESWE-944] Fixes wrong ssl database configuration

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/EmployerControllerShould.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/config/PageSerialization.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/EmployerController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/service/EmployerService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/unit/service/EmployerServiceShould.kt
This PR:
- Adds pagination to the Employers endpoint using Spring's PageModel serialization. If the **page** and/or **size**  are not informed, the values 0 and 10 are set, respectively.
=> [ESWE-946] Paginated employers list

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/ApplicationTestCase.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/EmployerControllerShould.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/EmployerTestCase.kt
This pull request refactors the Employer's acceptance test to reduce duplication. The structure of the `ApplicationTestCase` evolves and creates a new specialized `EmployerTestCase` so default values and general requirements are codified.
=> [ESWE-947] Refactors acceptance testing reducing duplication

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/employers/EmployersGetShould.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/employers/EmployersPutShould.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/employers/EmployersTestCase.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/JobsGetShould.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/JobsPutShould.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/JobsTestCase.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/application/CreateJobRequest.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/application/GetJobResponse.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/application/JobCreator.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/application/JobCreatorShould.kt
This first PR:
- Does an initial refactoring of tests.
- Renames the `title` attribute to `jobTitle` on the Jobs endpoint.
=> [Eswe 961] - Update job

src/test/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/employers/application/EmployerCreatorShould.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/application/JobCreatorShould.kt
This PR:
- Renames some Job tests to make them more expressive
- Adds new tests to validate the Job UUID
=> [ESWE-960] Job is created with valid UUID

.circleci/config.yml, .gitignore, Dockerfile, build.gradle.kts, gradle.properties, gradle/wrapper/gradle-wrapper.properties, helm_deploy/hmpps-jobs-board-api/Chart.yaml
Upgrade these:
1) Spring Boot: 3.3.3 <- 3.3.1
2) Kotlin: 2.0.20 <- 2.0.0
2) HMPPS gradle plugin: 6.0.4 <- 6.0.1
3) HMPPS SQS lib: 4.3.2 <- 4.0.1
4) Helm Chart: 0.2.1 <- 0.2.0
generic-service: 3.4 <- 3.3.1
generic-promethes-alerts: 1.8 <- 1.8.0
5) CircleCI orbs: 10 <- 9
6) Gradle: 8.10 <- 8.8
others:
- fix two warnings of Docker Build
=> [ESWE-1047] Upgrade Spring Boot to latest (and other dependencies)

.circleci/config.yml, helm_deploy/hmpps-jobs-board-api/values.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml
This PR ensures provision of Postgres RDS is available in preprod as well as prod:
- The instance is accessible by the Jobs Upload backend API application.
- When the Jobs Upload backend API is deployed in preproduction, it generates the database schema without errors.
- The database instance has scheduled a downtime
**Reviewers**
@jgomezzmoj
=> Deployment fix

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/ExpressionsOfInterestDeleteShould.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/ExpressionsOfInterestPutShould.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/ExpressionsOfInterestTestCase.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/ExpressionsOfInterestDelete.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/application/ExpressionOfInterestCreator.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/application/ExpressionOfInterestDeleter.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/application/ExpressionOfInterestCreatorShould.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/application/ExpressionOfInterestDeleterShould.kt
Pull existence check up for ExpressionOfInterest's deletion; Revise tests
1) pull existsById() up (for ExpressionOfInterest's deletion)
2) revise relevant tests (for ExpressionOfInterest's deletion)
3) add integration tests (invalid job ID) for ExpressionOfInterest creation and deletion
4) add job-existence check to existsById() at creation
=> [ESWE-1048] Expressions-of-interest - revise deletion and tests

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/commons/domain/RepositoryTestCase.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/domain/ArchivedRepositoryShould.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/domain/JobRepositoryTestCase.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/domain/TestPrototypes.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/domain/Archived.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/domain/ArchivedRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/domain/Job.kt, src/main/resources/db/migration/V1_1__start.sql
1. DB table for Job Archived
2. Domain entity and repository classes for Job Archived
3. Archived member of Job entity
4. Repository tests for Job Archived
=> [ESWE-1051] Job Archived DB, domain classes (entity and repository)

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/JobsGetShould.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/JobsTestCase.kt
This PR:
- Removes unused test functions
- Updates test function names to identify whether they validate single elements or lists.
=> [ESWE-865] Removes unused test function and improves naming

build.gradle.kts
by upgrading dependencies:
* org.apache.commons:commons-compress to 1.27.1
* org.xmlunit:xmlunit-core to 2.10.0
=> [ESWE-1067] Fix dependency vulnerabilities

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/MatchingCandidateGetShould.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/MatchingCandidateTestCase.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/JobsGet.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/application/MatchingCandidateJobRetriever.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/domain/MatchingCandidateJobRepository.kt
This PR:
- Enables matching candidate jobs default and custom pagination
- Allows optional filtering by one or more job sectors
=> [ESWE-865] List pagination and sectors filtering

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/ApplicationTestCase.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/MatchingCandidateGetShould.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/MatchingCandidateTestCase.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/JobsGet.kt
This PR enables matching candidate job sorting by:
- Job title
- Job closing date
=> [ESWE-865] Sorting matching candidate jobs by title and closing date

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/domain/JobRepositoryTestCase.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/domain/MatchingCandidateJobRepositoryJobDetailsShould.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/application/MatchingCandidateJobDetailsRetriever.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/domain/MatchingCandidateJobDetails.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/domain/MatchingCandidateJobRepository.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/application/MatchingCandidateJobDetailsRetrieverShould.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/application/TestBase.kt
to look up job details with prisonNumber, these have been added
1. repository's query, with a query's result DTO
2. retriever
=> [ESWE-858] View Job details repository and retriever

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/employers/EmployerMother.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/employers/EmployersGetShould.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/employers/EmployersPutShould.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/employers/EmployersTestCase.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/ArchivedTestCase.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/ExpressionsOfInterestTestCase.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/JobMother.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/JobsGetShould.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/JobsPutShould.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/JobsTestCase.kt
This PR extracts the creation logic of all testing job instances to a mother object. This object aims to provide dummy testing instances with enough creation granularity to cover all needed scenarios.
=> [ESWE-865] Jobs mother refactor

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/ApplicationTestCase.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/JobMother.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/JobsTestCase.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/MatchingCandidateGetShould.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/MatchingCandidateJobDetailsGetShould.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/MatchingCandidateJobDetailsTestCase.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/MatchingCandidateTestCase.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/JobsGet.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/employers/domain/Employer.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/application/ExpressionOfInterestCreator.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/application/ExpressionOfInterestDeleter.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/application/GetMatchingCandidateJobsResponse.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/application/JobCreator.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/application/MatchingCandidateJobRetriever.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/domain/ExpressionOfInterest.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/domain/Job.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/domain/MatchingCandidateJobRepository.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/application/ExpressionOfInterestCreatorShould.kt
This PR:
- Refactors some of the dummy data used on tests
- Provides an initial factory for test dummy object creation.
- Introduces a basic implementation for matching candidate listing.
=> [ESWE-865] Jobs mother refactor candidate matching

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/JobsTestCase.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/MatchingCandidateGetShould.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/application/ExpressionOfInterestDeleter.kt
This PR does some small refactors and adds missing tests to avoid problems with mixed expressions of interest among candidates and jobs.
=> [ESWE-865] Candidate matching with expressions of interest

helm_deploy/values-prod.yaml
fix the wrong indentations of "env:" at values-prod.yaml
=> [ESWE-1054] fix Prod config (ENV var)

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/employers/EmployerMother.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/JobsPutShould.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/employers/EmployersPut.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/employers/application/EmployerCreator.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/employers/domain/Employer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/employers/application/EmployerCreatorShould.kt
This PR fixes a bug that deletes all Jobs related after an Employer profile is updated.
=> [ESWE-1097] Fixes Employer profile edition, preventing deletion of related jobs

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/JobMother.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/application/CreateJobRequest.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/application/GetJobResponse.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/application/JobCreator.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/domain/Job.kt, src/main/resources/db/migration/V1_1__start.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/domain/JobMother.kt
This PR makes the field `Supporting Documentation Required` optional when creating or updating a Job.
=> [ESWE-959] Fixes Supporting Documentation Required field

src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/application/PostcodeLocationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/domain/PostcodesRepository.kt, src/main/resources/db/migration/V1_1__start.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/application/PostcodeLocationServiceShould.kt
This PR prevents that an existing postcode is saved twice.
=> [ESWE-865] Saving only non existing postcodes

src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/employers/EmployersGet.kt
revise API docs of `GET` `/employers`
=> [ESWE-1105] Revise API Docs (Employers GET)

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/applications/ApplicationMother.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/applications/ApplicationsGetShould.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/applications/ApplicationsTestCase.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/shared/application/ApplicationTestCase.kt
Add more cases to integration test of applications search
* filter by application status, job title or employer name, prisoner name
* order by job and employer or prisoner name
* custom pagination
=> [ESWE-888] Add more Integration tests of applications search (filters, sorting and pagination)

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/employers/infrastructure/EmployerRepositoryShould.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/infrastructure/JobRepositoryShould.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/domain/Auditable.kt
Fix the issue of (`Auditable`'s) `lastModifiedBy` is not getting updated in DB.
This has impacted `Job` and `Employer`.
=> [ESWE-1113] Fix Auditable `lastModifiedBy` not updating to DB

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/JobMother.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/MatchedJobClosingSoonTestCase.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/MatchedJobsClosingSoonGetShould.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/infrastructure/JobRepositoryTestCase.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/infrastructure/MatchingCandidateJobRepositoryShould.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/JobsGet.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/application/GetJobsClosingSoonResponse.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/application/MatchingCandidateJobRetriever.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/domain/MatchingCandidateJobRepository.kt
This PR add `/closing-soon` to endpoint `/jobs/matching-candidate`, which return a list of matched jobs closing soon, for the given prisoner (`prisonNumber` has been specified)
=> [ESWE-859] Matched jobs closing soon

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/MatchedJobClosingSoonTestCase.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/MatchedJobsClosingSoonGetShould.kt
This PR fixes a wrong test case (bad request) of Matched Jobs closing soon
=> [ESWE-859] fix test of Matched Jobs Closing soon

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/ExpressedInterestClosingSoonGetShould.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/ExpressedInterestClosingSoonTestCase.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/infrastructure/MatchingCandidateJobRepositoryShould.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/JobsGet.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/application/MatchingCandidateJobRetriever.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/domain/MatchingCandidateJobRepository.kt
This PR add Jobs of interesting closing soon endpoint at `/jobs/expressed-interest/closing-soon`
=> [ESWE-860] Jobs of interest closing soon

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/JobMother.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/JobsTestCase.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/MatchingCandidateGetShould.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/JobsGet.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/application/MatchingCandidateJobRetriever.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/domain/MatchingCandidateJobRepository.kt
This PR considers new scenarios, like when the release area or the radius is not provided.
=> [ESWE-865] Matching candidate job list without release area or search radius

.circleci/config.yml
Revise the schedule to run daily security tests
=> [ESWE-1127] Revise security test schedule

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/applications/infrastructure/ApplicationRepositoryShould.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/employers/infrastructure/EmployerRepositoryShould.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/infrastructure/JobRepositoryShould.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/infrastructure/PostcodeRepositoryShould.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/audit/domain/AuditedEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/domain/Auditable.kt, src/main/resources/db/migration/V1_3__ESWE-1128_enlarge_username_fields.sql
This PR enlarged username fields (createdBy, lastModifiedBy), changing length from 30 to 240
=> [ESWE-1128] Enlarge username fields

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/applications/infrastructure/ApplicationRepositoryShould.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/JobMother.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/domain/TestPrototypes.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/infrastructure/ArchivedRepositoryShould.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/infrastructure/ExpressionOfInterestRepositoryShould.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/shared/infrastructure/RepositoryTestCase.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/domain/Archived.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/domain/ExpressionOfInterest.kt, src/main/resources/db/migration/V1_4__ESWE-1131_add_audit_field.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/domain/JobMother.kt
This PR added audit field (`createdBy`) to _Archived Job_ and _Expression of Interest_.
=> [ESWE-1131] Add createdBy to Archived Job and Expression of Interest

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/applications/infrastructure/ApplicationAuditCleaner.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/applications/infrastructure/ApplicationRepositoryShould.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/applications/infrastructure/ApplicationRepositoryTestCase.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/config/TestJpaConfig.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/applications/ApplicationMother.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/dashboard/DashboardMetricsTestCase.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/dashboard/DashboardTestCase.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/dashboard/MetricsSummaryGetShould.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/infrastructure/JobRepositoryTestCase.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/shared/infrastructure/TestClock.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/applications/application/ApplicationMetricsRetriever.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/applications/application/GetMetricsSummaryResponse.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/applications/domain/ApplicationRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/applications/infrastructure/ApplicationMetricsRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/applications/infrastructure/ApplicationMetricsRepositoryImpl.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/config/HmppsJobsBoardApiExceptionHandler.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/dashboard/DashboardGet.kt
Add API endpoint `/dashboard/summary` for reporting metrics of dashboard summary
=> [ESWE-1147] Dashboard metrics - summary

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/applications/infrastructure/ApplicationRepositoryShould.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/applications/infrastructure/ApplicationRepositoryTestCase.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/dashboard/DashboardMetricsTestCase.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/dashboard/MetricsTotalApplicationsStageGetShould.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/applications/application/ApplicationMetricsRetriever.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/applications/application/GetMetricsApplicationCountByStatusResponse.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/applications/domain/ApplicationRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/applications/infrastructure/MetricsCountByStatus.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/dashboard/DashboardGet.kt
Add API endpoint `/dashboard/applications-stage` for reporting metrics of Total applications by application stage
=> [ESWE-1148] Dashboard metrics - Total applications by application stage

src/main/resources/db/migration/V1_5__ESWE-1147_add_dashboard_index.sql
Add index to application history (`applications_audit` table)
=> [ESWE-1147] Add index to application history

README.md, docker-compose.yml, helm_deploy/values-dev.yaml, src/main/resources/META-INF/additional-spring-configuration-metadata.json, src/main/resources/application-dev.yml
1. Refactor local run of application
2. Update README.md
=> [ESWE-1198] Update README, Refactor local run

README.md, docker-compose.yml, src/main/resources/application-localstack.yml, src/main/resources/application.yml
* run without queue: `dev` profile
* run with local queue: `local` profile group (with profiles `dev` plus `localstack`)
=> [ESWE-1167] Add `localstack`(`SQS`) for Integration queue

src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/config/IntegrationConfiguration.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/config/IntegrationProperties.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/employers/application/EmployerCreator.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/employers/domain/EmployerEvent.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/messaging/OutboundEventsPublisher.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/messaging/OutboundEventsService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/shared/application/OutboundEventsService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/shared/domain/OutboundEvent.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/shared/domain/OutboundEventsPublisher.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/shared/infrastructure/OutboundEventsQueuePublisher.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/time/DefaultTimeProvider.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/time/TimeProvider.kt, src/main/resources/application-localstack.yml, src/main/resources/application.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/employers/application/EmployerCreatorShould.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/application/TestBase.kt
Jobs Board Integration of `Employer`
* send event to queue for Employer-Created and Employer-Updated
* add relevant unit test cases
=> [ESWE-1167] Integration - send event for Employer creation/update

.circleci/config.yml, .gitignore, build.gradle.kts, docker-compose.yml, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/config/SqsTestConfig.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/employers/EmployersPutShould.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/shared/application/ApplicationTestCase.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/testcontainers/LocalStackContainer.kt, src/integrationTest/resources/application-test-containers-flyway.yml
* add `localstack` to integration test
* add integration tests for Employer Integration (creation, update event)
* add `awaitility` dependency to integration test (for verification with SQS async. client)
* add `localstack` to CircleCI `validate` job
=> [ESWE-1167] integration tests for Employer integration events

helm_deploy/values-dev.yaml, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/config/IntegrationProperties.kt, src/main/resources/application-localstack.yml, src/main/resources/application.yml
* enable Integration flow(s) (`api.integration.enabled`)
* switch to `IRSA` service account
* enable SQS queue (of Integration)
* remove configuration property `api.integration.outboundQueueName` (only used for local run)
=> [ESWE-1167] Enable Integration on `dev`

src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/employers/EmployersGet.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/ExpressionsOfInterestDelete.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/ExpressionsOfInterestPut.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/JobsGet.kt
for retrieving employer/job details and editing expression-of-interest
=> [ESWE-1208] Setup Role-based access of some API endpoints

src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/application/MatchingCandidateJobRetriever.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/time/TimeProvider.kt
some tests were broken due to "today" not mocked
=> [ESWE-1180] Fix broken tests

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/employers/EmployerMother.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/employers/EmployersPutShould.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/employers/infrastructure/EmployerRepositoryShould.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/config/HmppsJobsBoardApiExceptionHandler.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/employers/EmployersPut.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/employers/application/EmployerCreator.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/employers/application/EmployerValidationException.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/employers/domain/Employer.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/employers/domain/EmployerRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/shared/application/ValidationExceptions.kt, src/main/resources/db/migration/V1_7__ESWE-1226_unique_employer_name.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/employers/application/EmployerCreatorShould.kt
- Validate duplicate employers' name
- Add unique constraint to employer's name
=> [ESWE-1226] Validate duplicate employers' name

helm_deploy/hmpps-jobs-board-api/values.yaml
- extract connecting string to secrets
- revise actual string at the externalised secrets
=> [ESWE-1222] Fix appinsights errors

helm_deploy/values-dev.yaml
Add env var access role in helm (dev)
=> [ESWE-1082] Add helm env var access role

build.gradle.kts
- Spring Boot `3.4.4` along with `gradle-spring-boot` `8.0.0`
- Kotlin `2.1.20`
- HMPPS SQS lib `5.4.2`
=> [ESWE-1267] Update dependencies

build.gradle.kts, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/sar/application/SubjectAccessRequestService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/sar/application/SubjectAccessRequestServiceTest.kt
Sort data by in descending chronological order
=> [ESWE-1082] format date; sorting

build.gradle.kts, gradle/wrapper/gradle-wrapper.properties
* Spring Boot to `3.4.5` (was `3.4.4`)
* DPS SB plugin to `8.1.0` (was `8.0.0`)
* SQS lib to `5.4.4` (was `5.4.2`)
* Gradle `8.14` (was `8.12.1`)
=> [ESWE-1307] Upgrade dependencies

.github/workflows/pipeline.yml, src/integrationTest/resources/application-test-containers-flyway.yml, src/integrationTest/resources/application-test-containers.yml
- Fix localstack SQS config
- Fix DB config issues at integration tests (set defaults instead of passing in)
=> [ESWE-1367] Fix GHA build/test issues

build.gradle.kts
Upgrade:
* Spring Boot plugin `9.0.0` (was `8.3.7`)
=> [ESWE-1414] Upgrade dependencies for OWASP scan's fix

build.gradle.kts
- plugin `gradle-spring-boot` to `9.1.1` (was `9.0.2`)
=> [ESWE-1462] Upgrade dependencies
