ministryofjustice/hmpps-jobs-board-api

.trivyignore, build.gradle.kts, settings.gradle.kts
Reviewed Gradle's build with the following changes:
- Upgraded HMPPS spring boot plugin to the last stable version (v6.0.0)
- Upgrade Kotlin Spring and JPA plugins to the last stable version (v2.0.0)
- Remove unnecessary plugins
- Remove unnecessary global dependencies
- Update global dependencies to the last stable version
- Modify the definition of the Integration test suite to align with Gradle's jvm-test-suite plugin documentation
- Remove unnecessary tasks and Kotlin definitions.
- Updated Trivignore file (Not sure if it is even necessary to be pushed to the repository)
- Removed unnecessary integration tests sources in Gradle's settings
=> ESWE-831 Update and clean build Gradle

helm_deploy/hmpps-jobs-board-api/Chart.yaml
The purpose of this PR is to update the following Helm dependencies of this project:
- generic-service
- generic-prometheus-alerts
I'm using as a reference the HMPPS Helm chart releases page:
https://github.com/ministryofjustice/hmpps-helm-charts/releases
=> ESWE-831 Upgrade Helm dependencies to last stable versions

helm_deploy/hmpps-jobs-board-api/values.yaml
After creating the Dev database the app needs to inject the database details from the secrets stored on the namespace.
=> ESWE-831 Adds Helm database environment variables

docker-compose.yml
This PR modifies the way we use Docker compose locally, so it now will start the app and the database in one go.
The changes proposed are:
- Removes obsolete `version` directive
- Adds a database container, so it will be available for the app
- Configures the App with the local database parameters
- Configures the App on the same network of the database
- Configures the App to use DEV's auth endpoint
=> [ESWE-831] Updates app config and adds database

docker-compose.yml, src/main/resources/application-developer.yml
The following PR improves some aspects of local development:
- Set standard ports for the app and the database in the Docker compose script
- Adds Dev auth URL for local development
- Deletes deprecated FlyWay _initOnMigrate_ attribute
=> [ESWE-831] Improve development config

src/main/resources/application-developer.yml, src/main/resources/application.yml
This PR removes some unnecessary JPA configuration options from the Spring boot application:
- Dialect is not necessary
- The same configuration that is in developer is provided from the root application configuration. It's not necessary to duplicate it.
=> [ESWE-831] Removes unnecessary JPA Springboot configuration

.circleci/config.yml, build.gradle.kts, gradle/wrapper/gradle-wrapper.properties, gradlew, src/main/resources/application-developer.yml, src/main/resources/application.yml
The purpose of this pull request is to[ update the following Kotlin template dependencies](https://mojdt.slack.com/archives/CTLQ5TCNN/p1719414257905729):
- CircleCI orb plugin from v8 to v9
- HMPPs Gradle Spring Boot from 6.0.0 to [6.0.1](https://github.com/ministryofjustice/dps-gradle-spring-boot/blob/main/release-notes/6.x.md)
- HMPPS Spring Boot SQS from 2.1.1 to [4.0.1](https://github.com/ministryofjustice/hmpps-spring-boot-sqs/blob/main/release-notes/4.x.md) 
- Removes the use of a fixed version of PostgreSQL
- Upgrades Gradle wrapper from 8.7 to 8.8
- Removes unnecessary PostgreSQLDialect configuration
=> [ESWE-831] Kotlin template updates

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/ApplicationTestCase.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/EmployerControllerShould.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/EmployerController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/entity/EntityId.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/unit/entity/EntityIdShould.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/unit/service/EmployerServiceShould.kt
This pull request:
- UUID validation is added at the entity, service, and controller levels.
- Extend acceptance testing functions to test error scenarios
- Some minor test refactor
=> [ESWE-942] Adds UUID validation when an Employer is created

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/ApplicationTestCase.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/EmployerControllerShould.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/EmployerController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/service/EmployerService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/unit/service/EmployerServiceShould.kt
This PR:
- Adds a different Employers endpoint behaviour when a resource item is updated. The consumer will receive a 200 OK HTTP status instead of a 201 Created.
- EmployerService exposes a new method to check if an Employer already exists.
- Fixes errors on the acceptance test base assertions
- Refactored some names to remove duplication and make them more expressive
=> [ESWE-942] Adds a different behaviour for Employer update

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/EmployerControllerShould.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/EmployerController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/service/EmployerService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/unit/service/EmployerServiceShould.kt
The purpose of this pull request is to provide a very primitive capability of the `Employers` endpoint to return a list of all items stored in the database:
- Adds the ability to the endpoint to return a simple list of `Employers`
- Does some test refactor to use asserThat over `asserEquals` or `assertTrue`/`assertFalse`
Out of scope:
- Filtering
- Pagination
- Ordering
=> [ESWE-964] Adds the ability to return a list of all Employers

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/EmployerControllerShould.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/EmployerController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/repository/EmployerRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/service/EmployerService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/unit/service/EmployerServiceShould.kt
This PR:
- Adds name and sector filtering
- Uses the Springframework `Pageable` static factory to produce `pageRequest` objects
- Small refactors on service tests.
=> [ESWE-945] Adds name and sector filtering on the Employers endpoint

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/EmployerControllerShould.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/repository/EmployerRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/service/EmployerService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/unit/service/EmployerServiceShould.kt
This PR modifies the repository method names so the name and sector filters are applied, ignoring the text case. The testing is done from the acceptance testing point of view. Some of the existing acceptance tests are also modified to test this behaviour implicitly.
=> [ESWE-945] Name and sector Employers filtering ignores text case

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/EmployerControllerShould.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/repository/EmployerRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/service/EmployerService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/unit/service/EmployerServiceShould.kt
This PR updated the Employer's search to allow incomplete name filters. Each employer whose name contains the string passed as a filter will be returned.
=> [ESWE-945] Updates Employers filter to allow search with incomplete names

build.gradle.kts, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/ApplicationTestCase.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/EmployerControllerShould.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/EmployerController.kt
This PR adds sorting to the list of Employers:
- By default, the list of Employers is sorted by name
- By default, the order is ascendent.
- The order can be descendent using `sortOrder=desc`
- The sorted field can be changed to date added using `sortby=createdAt`
- The sort and order fields can be used with pagination and filters.
=> [ESWE-947] Adds sorting to the list of Employers

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/ApplicationTestCase.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/config/TestJpaConfig.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/JobsGetShould.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/JobsTestCase.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/application/GetJobResponse.kt
This PR adds the audit attribute `createdAt` when a Job is retrieved.
It also adds more technical debt that must be addressed in the following deliveries. That debt has increased in how the code manages the fake data as requests, responses, objects and time.
A proper refactor and use of proper creational patterns, like factories or Object Mother, will reduce duplication and make our tests simpler.
=> [ESWE-960] Get job contains createdAt attribute

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/ApplicationTestCase.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/employers/EmployersTestCase.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/JobsGetShould.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/employers/EmployersGet.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/JobsGet.kt
This is a small initial PR for the Jobs list. It implements the minimum test to check that the endpoint wiring is in place and the headers are present.
=> [Eswe-964] Get empty paginated job list

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/ApplicationTestCase.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/employers/EmployersGetShould.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/employers/EmployersPutShould.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/employers/EmployersTestCase.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/JobsGetShould.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/JobsPutShould.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/JobsTestCase.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/JobsGet.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/employers/domain/EmployerRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/application/JobRetriever.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/domain/JobRepository.kt
This PR:
- Allows to filter Jobs list by Job sector
- Allows to filter Jobs list by Job sector AND Job title / Employer name combined. Even if the second one is not complete
- It allows all filtering described combined with custom and default pagination.
=> [ESWE-962] Filter jobs by Job title / Employer name AND Job sector

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/ApplicationTestCase.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/employers/EmployersGetShould.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/JobsGetShould.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/JobsTestCase.kt
This PR checks that:
-  When `sortedBy` is passed as a parameter with the value `createdAt`:
- If the value for the `sortOrder` parameter is empty or missing, it will be `asc` by default, meaning that the job list will be sorted by the creation date (`createdAt`) in ascending order.
- If the value for the `sortOrder` parameter has a `desc` value, the job list will be sorted by the creation date (`createdAt`) in descending order.
=> [ESWE-963] Job list sorted by date added

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/JobsGetShould.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/application/JobRetriever.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/domain/Job.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/domain/JobRepository.kt
The expected logic condition of the Jobs list search must be:
`Job sector AND (JobTitle OR Employer name)`
However, the result was not expected because of the limitations of the JPA Query Methods. We observed instead the following behaviour:
`Job sector AND JobTitle OR Employer name`
The existing tests didn't catch the unexpected behaviour and also needed a revisit.
This PR fixes the logic and the tests. It replaces the existing JPA Query Method with a more specific Spring Data JPA @Query that allows the desired logic condition.
=> [ESWE-962] Fixes the jobs list filter logic

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/ApplicationTestCase.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/EmployerRepositoryShould.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/JobRepositoryShould.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/employers/EmployersGetShould.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/employers/EmployersTestCase.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/JobsGetShould.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/JobsTestCase.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/employers/application/EmployerCreator.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/employers/application/GetEmployerResponse.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/employers/domain/Employer.kt, src/main/resources/db/migration/V1_1__start.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/employers/application/EmployerCreatorShould.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/employers/application/EmployerRetrieverShould.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/application/TestBase.kt
This PR
* Added audit field "modifiedAt" to entity "Employer"
* Enabled JPA Auditing for Employer; (replacing manual timestamping)
* Fixed broken tests (of Job, Employer) due to Employer changes above
* Added new test cases for Employer Repository (around the two auditing timestamp fields)
* Removed some unused properties/imports (tidy-up)
* The new audit field (Employer modifiedAt) is a breaking change to DB
=> [ESWE-942] Add/Revise audit fields of Employer

helm_deploy/values-preprod.yaml
As per the [MoJ’s “creating a database” guide](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/deploying-an-app/relational-databases/create.html#non-production), non-production databases must be stopped out of working hours.
Environment: **PREPROD**
=> [ESWE-1055] Schedule rds downtime

helm_deploy/values-preprod.yaml
This PR fixes a missing 'auth' part of the path, preventing the app from properly authenticating users.
=> [GREEN] Fixes HMPPS preproduction oauth path

src/main/resources/application.yml
This PR fixes the path defined for the `token-uri` configured for preproduction and production.
=> [ESWE-1059] Fixes HMPPS preproduction oauth token path

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/ExpressionOfInterestRepositoryShould.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/application/ExpressionOfInterestCreator.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/application/ExpressionOfInterestDeleter.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/domain/ExpressionOfInterest.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/domain/ExpressionOfInterestRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/domain/JobPrisonerId.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/application/ExpressionOfInterestCreatorShould.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/application/ExpressionOfInterestDeleterShould.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/domain/JobPrisonerIdShould.kt
Refactoring for common codes
ExpressionOfInterestId identity class has been renamed to JobPrisonerId to denote an identity of job-prisoner relation. 
Existing usage: Expression of Interest
Next usage: Job Archive
=> [ESWE-1051] Rename ExpressionOfInterestId for code sharing

docker-compose.yml, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/MatchedJobsGetShould.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/MatchedJobsTestCase.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/JobsGet.kt
This PR sets the minimum infrastructure to enable the new `jobs/matching-candidate` endpoint.
For now, it will return an empty paginated list, allowing initial wiring testing in Dev and Preprod environments.
=> [ESWE-865] Empty candidate matching jobs list

src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/config/HmppsJobsBoardApiExceptionHandler.kt
Add back default handlers for 404 and 403 errors
from kotlin template (500-error were thrown if without these)
=> [ESWE-858] fix HTTP error codes

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/ApplicationTestCase.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/ArchivedDeleteShould.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/ArchivedTestCase.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/ExpressionsOfInterestDeleteShould.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/ExpressionsOfInterestTestCase.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/JobsTestCase.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/MatchingCandidateTestCase.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/application/GetMatchingCandidateJobsResponse.kt
This PR:
- Adds the missing Job ID on each list item.
- Makes 'expression of interest' test assertion functions access wider so it can be used to set specific scenarios of matching candidates.
=> [ESWE-865] Matching candidates list provides job ID

build.gradle.kts
CVE-2024-38816 : upgrade Spring Boot
CVE-2024-45801 : upgrade dependencies (for OpenAPI) 
**Spring Boot** 3.3.4 (framework 6.1.13) has addressed this vulnerability (CVE-2024-38816)
upgrade these dependencies (CVE-2024-45801) 
* springdoc-**openapi**-starter-webmvc-ui to 2.6.0 (from 2.3.0), 
including these:
* **swagger-ui** to 5.17.14 (from 5.10.3)
* **dompurify** to 3.1.4 (from 3.0.6)
=> [ESWE-1074] Upgrade Spring Boot and dependencies for fixing vulnerabilities 

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/employers/EmployersGetShould.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/employers/EmployersTestCase.kt
This small PR refactors the Employer's tests so they can create multiple elements in just one command.
=> [ESWE-865] Enables multiple test Employer creation

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/EmployerRepositoryShould.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/ExpressionOfInterestRepositoryShould.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/JobRepositoryShould.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/JobMother.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/JobsGetShould.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/JobsTestCase.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/domain/ArchivedRepositoryShould.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/domain/JobRepositoryTestCase.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/domain/MatchingCandidateJobRepositoryJobDetailsShould.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/domain/TestPrototypes.kt
This PR continues with the refactors to simplify the access to the data used for creation and assertion in our tests.   It moves all the logic to create the expected test list items to the job mother object, removing duplicated code.
=> [ESWE-865] Job mother refactor list items

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/ApplicationTestCase.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/ArchivedTestCase.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/MatchingCandidateGetShould.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/domain/MatchingCandidateJobRepository.kt
This PR:
- Proposes a new way to name Candidate Matching test naming, reducing duplication and structuring them using nested classes.
- Filters jobs that have not been archived for a candidate.
- Removes duplication and makes tests more compact for `archiving` and `expressions of interest`, extending the scenario's setup to cover a larger area.
=> [ESWE-865] Candidate matching avoid archived jobs

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/MatchingCandidateGetShould.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/MatchingCandidateTestCase.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/config/HmppsJobsBoardApiExceptionHandler.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/application/MatchingCandidateJobDetailsRetriever.kt
The matching candidate endpoints need the `Prison Number` parameter to be present.  This small PR adds proper message and HTTP status to model this error.
=> [ESWE-865] Candidate matching returns an error on missing prison number parameter

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/JobsGetShould.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/JobsTestCase.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/config/HmppsJobsBoardApiExceptionHandler.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/application/JobNotFoundException.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/application/JobRetriever.kt
This PR is necessary to fix a bug. When a job doesn't exist, it will return a 404 Not Found.
=> [ESWE-965] View job returns not found

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/applications/infrastructure/ApplicationRepositoryShould.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/applications/infrastructure/ApplicationRepositoryTestCase.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/applications/ApplicationMother.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/applications/ApplicationsByPrisonerTestCase.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/applications/ApplicationsTestCase.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/applications/OpenApplicationsGetShould.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/applications/application/ApplicationByPrisonerRetriever.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/applications/application/GetApplicationsByPrisonerResponse.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/applications/domain/ApplicationRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/applications/domain/ApplicationStatus.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/applications/ApplicationsGet.kt
This PR add new endpoint `/applications/open` under `/applications` for listing all open applications of given prisoner
- Pagination has been added. 
- Pagination parameters are optional
- Repository, retriever and response are shared with closed application (upcoming changes next)
=> [ESWE-861] Open applications

src/main/resources/db/migration/V1_1__start.sql
This PR fixes a mistake in the postcode field size on the database. The official size is between six and eight characters, including a middle empty space.
=> [ESWE-865] Fixes postcode size from 7 to 8

src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/application/PostcodeLocationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/domain/PostcodesRepository.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/application/PostcodeLocationServiceShould.kt
If the OS Places API service is down, the coordinates for a postcode won't be available. In that case, we'll store null values.
This PR provides a self-healing feature. Every time a postcode is retrieved when saving or updating a Job, if the code has its coordinates to null, the service will try to recover them again.
=> [ESWE-865] Updating null postcode coordinates

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/employers/EmployersPutShould.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/employers/EmployersTestCase.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/employers/application/CreateEmployerRequest.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/employers/domain/Employer.kt, src/main/resources/db/migration/V1_1__start.sql, src/main/resources/db/migration/V1_2__ESWE-1105_enlarge_employers_description.sql
This PR increase the maximum length of employer's description from 500 to 1000.
1. DB column length is revised.
2. Validation has been added to API/controller
=> [ESWE-1105] Increase Employer description length to 1000 (from 500)

build.gradle.kts, gradle/wrapper/gradle-wrapper.properties, helm_deploy/hmpps-jobs-board-api/Chart.yaml, jobs-board-suppressions.xml
Upgrade framework and dependencies for resolving vulnerabilities.
- upgrade Spring Boot to `3.3.5` (and Spring Framework `6.1.14`); (was `3.3.4` and `6.1.13`)
- upgrade Kotlin to `2.0.21` (was `2.0.20`)
- suppress vulnerabilities of DOMPurify (as not applicable, testing only)
=> [ESWE-1106] Upgrade Spring Boot and suppress inapplicable vulnerabilities

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/JobMother.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/MatchingCandidateJobDetailsGetShould.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/shared/application/ApplicationTestCase.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/shared/infrastructure/OSPlacesMockServer.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/JobsGet.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/application/MatchingCandidateJobDetailsRetriever.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/domain/MatchingCandidateJobRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/domain/Postcode.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/infrastructure/OsPlacesApiDPA.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/infrastructure/OsPlacesApiWebClient.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/application/MatchingCandidateJobDetailsRetrieverShould.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/application/PostcodeLocationServiceShould.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/infrastructure/OsPlacesApiWebClientShould.kt
This PR aims to introduce the distance calculation between two locations identified by a postal code. We must first obtain the coordinates defining each postcode to do this calculation.
Each postcode has a pair of coordinates XY associated that defines its reference centre point. To obtain it, we use a third-party service, in our case [OS Places API](https://osdatahub.os.uk/docs/places/technicalSpecification)
The keys for use on our environments have been requested via the [#ask-operations-engineering](https://mojdt.slack.com/archives/C01BUKJSZD4/p1728314239141029) Slack channel.
The keys are stored on Kubernetes as secrets.
One of the essential architectural decisions taken here is to store the postcodes and their coordinates in our database as a primitive cache. The main reasons were:
- …
=> [ESWE-858] Matching candidate job details distance calculation

.circleci/config.yml
run `security` scans earlier to avoid peak hours, which may result in errors like `TOOMANYREQUESTS` while downloading vulnerability DB
=> [ESWE-1106] Revise schedule of security scans

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/JobMother.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/MatchingCandidateGetShould.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/MatchingCandidateJobDetailsGetShould.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/MatchingCandidateTestCase.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/shared/application/ApplicationTestCase.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/JobsGet.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/application/GetMatchingCandidateJobsResponse.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/application/MatchingCandidateJobRetriever.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/domain/MatchingCandidateJobRepository.kt
This is a small PR to establish the initial wiring of the distance calculation on the Candidate Matching list.
Now, the calculation is fully functional.
The filter based on distance radius has not been implemented yet.
=> [Eswe-865] Matching candidate job list distance calculation

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/domain/PostcodeMother.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/infrastructure/MatchingCandidateJobRepositoryShould.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/application/MatchingCandidateJobRetriever.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/domain/MatchingCandidateJobRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/domain/Postcode.kt
This PR contains a few fixes
1. `Postcode` length to 8 (from 7)
2. `closingDate` check is added to matched job
3.  Default sorts have been added to improve test results' stability.
=> [ESWE-867] Fixes of matching/matched/closing jobs and postcodes

build.gradle.kts, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/infrastructure/OsPlacesApiWebClient.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/infrastructure/OsPlacesApiWebClientShould.kt
This PR:
- Assures that a fallback object with the original postcode and null coordinates is returned in case of any problem calling the OS Places API or processing the response.
- It now adds log messages to enable future debug and specific error handling. The tests expect the exception message to be logged as part of the error message.
=> [ESWE-865] Matching candidate unexpected error returns fallback postcode

jobs-board-suppressions.xml
suppress CVE-2024-48910 via test-only dependency Wiremock bundle
=> [ESWE-1129] Suppress vulnerability of test-only dependency

src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/MatchingCandidateGetShould.kt, src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/controller/jobs/PostcodeMother.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/domain/MatchingCandidateJobRepository.kt
This PR fixes an unwanted behaviour on the backend Matching Candidates endpoint for prisoners with a special 'No fixed abode' release area postcode (NF1 1NF) assigned and any Search Radius provided. With these two values passed, the result will always be an empty list. It's interesting to note that if Search Radius is not provided, the list is generated correctly.
In summary, when a postcode has no associated coordinates for any reason, the Search Radius filter must be avoided and should not affect the filtering process.
This PR solves this behaviour by also checking that the coordinates related to the release area are not null.
=> [ESWE-1137] 'No fixed abode' release area postcode and any Search Radius should return Job list

build.gradle.kts, gradle/wrapper/gradle-wrapper.properties
Upgrade dependencies:
* Upgrade HMPPS Spring Boot Gradle plugin to `6.0.9` (was `6.0.8`)
* Upgrade Gradle wrapper to `8.11` (was `8.10.2`)
* Upgrade `netty-common` to `4.1.115.Final` (was `4.1.114.Final`) (via Spring Boot plugin upgrade)
* Upgrade `hmpps-sqs-spring-boot-starter` to `5.1.1` (was `4.3.2`)
=> [ESWE-1158] MJMA fix vulnerability and upgrade dependency

helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml
This PR update the severity and thus alert can be sent to default slack channels (prod, non-prod)
=> [ESWE-1169] fix severity of prometheus alerts

build.gradle.kts, jobs-board-suppressions.xml, src/main/kotlin/uk/gov/justice/digital/hmpps/jobsboard/api/jobs/domain/MatchingCandidateJobRepository.kt
- upgrade gradle-spring-boot plugin (`7.1.3`, with Spring Boot to `3.4.3`)
- upgrade `swagger-ui` to `5.20.0`
- upgrade sqs lib to `5.3.2`
- upgrade `springdoc-openapi-starter-webmvc-ui` to `2.8.5`
- suppress for `wiremock-standalone`
- workaround JPA bug (of `3.4.3`) 
workaround taken from https://github.com/spring-projects/spring-data-jpa/issues/3784
=> [ESWE-1258] Upgrade dependencies; Add suppression; workaround for JPA issue
